### ISSUE TITLE
Allow per project cache

### ISSUE THREAD

**Issue by buchgr** [buchgr/bazel-remote#15]
@BenTheElder mentioned to me that k8s is using a different remote cache for different projects and they distinguish between projects via a path component in the URL:

```https://cache.com/<project name>/(ac|cas)/```

I think that's a good idea and I believe @nicolov already laid the foundations for that.

**Comment by gjasny** [comment]
I started a prove-of-concept patch for on-disk storage here: https://github.com/gjasny/bazel-remote/tree/project_name

I noticed that for `cas` objects the cache enforces that the key equals the hashed content, so adding project name support there does not make much sense.

**Comment by BenTheElder** [comment]
the CAS only needs to enforce this for the last segment in the URL, so it's pretty easy to do this. there's an implementation here that inspired this issue: https://github.com/kubernetes/test-infra/tree/master/greenhouse

**Comment by sitsofe** [comment]
Looking through some logs with this in place I see the following:
```
020/09/08 11:44:29 REMAP AC HASH ed3360a7998f204de2c2f3311a2d8563d4f87bdfb9b4b442daee115f9c0bdb8a : centos-v2-Amd => 4699610a00158646b15c49ae315da98c
658db3cd2b0f376cc48de0c65f692993
2020/09/08 11:44:29  PUT 200     X.X.X.X /centos-v2-Amd/ac/ed3360a7998f204de2c2f3311a2d8563d4f87bdfb9b4b442daee115f9c0bdb8a
2020/09/08 11:44:29 S3 UPLOAD bazel-remote-prod bazel/cas/929d6d967df38d7d70128171a34ea8794603e05f5689d7996d06639eb05375b7 OK
2020/09/08 11:44:29 REMAP AC HASH a9c38c68068a703d5a3bcbba3729d0f21d78f515ef91c88fb5ebf798389caeaa : centos-v2-Amd => 105a6b03847b7df71ba1f2c7f3769f88
69405aa859abf4965344ef1e81cb7902
2020/09/08 11:44:29 S3 UPLOAD bazel-remote-prod bazel/cas/ed3360a7998f204de2c2f3311a2d8563d4f87bdfb9b4b442daee115f9c0bdb8a OK
```

- 4699610a00158646b15c49ae315da98c was mangled to ed3360a7998f204de2c2f3311a2d8563d4f87bdfb9b4b442daee115f9c0bdb8a
- `PUT 200     X.X.X.X /centos-v2-Amd/ac/ed3360[...]` happens because the original request path is what is logged and that doesn't contain the mangled hash
- `2020/09/08 11:44:29 S3 UPLOAD bazel-remote-prod bazel/cas/ed3360[...] OK` is the one I don't understand. Why would we want to put the object to S3 with the original hash rather than a mangled one?

**Comment by mostynb** [comment]
@sitsofe: `2020/09/08 11:44:29 S3 UPLOAD bazel-remote-prod bazel/cas/ed3360[...] OK` is a "CAS" blob (identified by the SHA256 of the data), which we do not mangle because the risk of key collision is extremely small.

This flag only mangles "AC" hash keys, which are prone to key collisions if the client can't hash all of the inputs.
