### ISSUE TITLE
bazel-remote uses all available memory.

### ISSUE THREAD

**Issue by mehmetg** [buchgr/bazel-remote#151]
bazel-remote uses all available memory 
`"args": ["--max_size=97","--tls_enabled=false"]`
(using the docker image from docker hub)
Is this intended? 
![Screen Shot 2020-01-02 at 12 49 32 AM](https://user-images.githubusercontent.com/1885791/71658733-fb21da00-2cf9-11ea-8ac3-c5493f6fe870.png)

**Comment by mostynb** [comment]
I don't have much experience with docker- what do the two lines represent in this graph? Both the green and yellow are labelled "bazel-remote-cache".

**Comment by mehmetg** [comment]
Sorry about that. The green one is another instance. The yellow one is the memory usage of the instance with 16GB memory available. 
What I have observed is that the server quickly allocates all that it can and holds on to it.

**Comment by mostynb** [comment]
That figure seems significantly higher than my bazel-remote instances (though I'm not using docker). Do you see this behaviour when building any opensource projects that use bazel, so I can try to reproduce it locally? Also, how large are the codebases that you're building, and how many clients are building simultaneously?

**Comment by mostynb** [comment]
I created an experimental image to mostynb/bazel-remote-cache on dockerhub, built from this branch:
https://github.com/mostynb/bazel-remote/tree/mostynb_dockerhub

If you run that with `-p 127.0.0.1:6060:6060` then it allows profiling, maybe you can use this to check if this is a memory leak? eg run this new docker image and start using the cache, then once you see the high memory usage:
`go tool pprof -png http://localhost:6060/debug/pprof/heap > heap-profile.png` and then attach the image here.

**Comment by buchgr** [comment]
I agree with what @mehmetg said. A possible explanation for the behavior is that bazel-remote keeps metadata of its cached contents in memory. So once the cache fills up to its maximum size the steady-state memory usage should roughly remain the same.

**Comment by mostynb** [comment]
16G sounds like a lot for metadata, though it depends on the scale of course. @mehmetg: how are you creating this graph btw?

**Comment by buchgr** [comment]
Any news @mehmetg ?

**Comment by Zetten** [comment]
I've also seen some fairly strange behaviour for which I was considering raising a new issue, but it feels like there might be something related here.

I'm operating bazel-remote in a Kubernetes cluster. Our use case is fairly simple: a 40 GB persistent volume (running on AWS; it's a gp2 EBS volume), and bazel-remote running with `--max_size=39`. I'm running a locally-built image of commit 06ee5c920d92a33ea16011ede16f186f37f1ccf8.

Our issue is expressed in leaky disk usage, but we have seen similar unexpectedly high memory usage:

![image](https://user-images.githubusercontent.com/111609/73455428-f76c8c00-4367-11ea-81e7-496eff2da4e6.png)

(@mostynb The graph is from Grafana, as part of [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) collecting and visualising metrics across the cluster. AFAIK the memory usage is retrieved directly from the container runtime. I imagine @mehmetg's graph was produced similarly.)

It's a risk to set any kind of `resources.limits.memory` value on the Pod, because it will quite happily try to over-allocate and get OOMkilled. Assuming it's not a real memory leak, it would be nice if bazel-remote could use the process cgroup memory limit as an input to LRU cleanup.

My possibly-related issue presents itself in our build logs with many, many messages along the lines of:
```2020-01-28 15:09:25.423   WARNING: Writing to Remote Cache:
2020-01-28 15:09:25.423   io.grpc.StatusRuntimeException: UNKNOWN: write /data/cas/18/18a03a67f6087e6a07d004dd803ecde8f1b7445a455548325ca5faaa4f1a0134.tmp: no space left on device
```

Checking manually, the volume under the cache is indeed full. Periodically checking `/status` HTTP endpoint reports the current size and limit as expected - i.e. bazel-remote _thinks_ it's deleting entries from the cache to stay within the limit. However it simply doesn't seem to be removing the files from the disk underneath.

Interestingly, if I use the latest pushed Hub image (commit 44720790708c17ec2425b1a7c125721880bc9d60) I don't have this issue - the files are cleaning themselves up nicely and staying within the configured limit. So it's possibly a new issue introduced between https://github.com/buchgr/bazel-remote/compare/44720790708c17ec2425b1a7c125721880bc9d60..06ee5c920d92a33ea16011ede16f186f37f1ccf8.

Perhaps this (new) file leak is exposing an existing memory leak?

**Comment by mostynb** [comment]
@Zetten: re disk usage, bazel-remote keeps track of the size of each of the blobs and their total, but this is a low estimate of the actual size on disk. Can you try setting a lower value for --max_size, maybe 35, and see if that helps and report back here? I will try to put together some stress tests in the meantime.

**Comment by mostynb** [comment]
@Zetten: I haven't been able to reproduce anything unusual yet, with a cache dir on a ~1.2G loopback filesystem and --max_size 2. bazel-remote eventually fails to write new files as expected, but the numbers from the status json still look correct, and the numbers in a heap profile are pretty small.

If you're using docker and want to try taking a heap profile snapshot, then IIRC you can add `--profile_port 7070 --profile_host 0.0.0.0` to the bazel-remote args, and -p 7070:7070 to the docker run args, and once bazel-remote is in this weird state run: wget http://localhost:7070/debug/pprof/heap ; go tool pprof -png heap > heap.png and share any interesting results here.

**Comment by buchgr** [comment]
@Zetten how does this graph continue? will it allocate even more memory?

**Comment by Zetten** [comment]
@mostynb I've observed the same behaviour with `--max_size 1` and a 5 GiB volume, so I don't think it's strictly a case of the files spilling over, or GB/GiB differences. I've also seen the same issue in a local Kubernetes (microk8s) deployment, so I don't think it's a quirk of EBS volumes dropping syscalls or anything like that.

Are you testing with the Hub image, or a local build and/or a different commit?

@buchgr This particular graph seems to stick at ~3 GB since I switched to the Hub image (commit 4472079 - which doesn't cause the disk usage issue). I'll keep an eye on it over the next few days as more builds run - we're quite low throughput at the moment. The metric is reported from kubelet/cadvisor as `container_memory_working_set_bytes`.

Next week I'll start playing with a test environment with profiling enabled, using the latest master.

**Comment by buchgr** [comment]
What's the definition of `container_memory_working_set_bytes`?. Could it be a problem with the metric?

**Comment by Zetten** [comment]
Good question. I know it's supposedly the metric that Kubernetes will use to invoke the OOMKiller if the container exceeds its configured limits, but not much more than that.

I'll dig in and compare the various metrics reported via both bazel-remote and k8s itself when I can set up the profiler. [This](https://medium.com/faun/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d) and [this](https://bwplotka.dev/2019/golang-memory-monitoring/) look promisingly informative.

**Comment by mostynb** [comment]
@Zetten: I mostly test "regular" builds on bare metal, not using docker. The tests I ran last night were a build made from the tip of master but with some extra logging statements.

Re memory usage, it sounds like it might be worth comparing the graphs with GODEBUG=madvdontneed=1 or with a locally-built docker image using go1.11 (edit the Dockerfile).

Re disk usage, the estimated disk usage is not so inaccurate that it would be under 1G of total blob bytes, but 5G on disk. Next time it's in this state can you save a copy of bazel-remote's /status json, and corresponding direct measurements? eg `du -sh your/cache/dir` for the actual usage, `df -h` for the filesystem's percent usage, `find your/cachedir -type f | wc -l` for the number of files in the cache.

**Comment by Zetten** [comment]
I've been testing again, starting with looking for this disk space issue (which is quicker to reproduce), under the theory it might be linked to the memory issue.

I started by setting up a new, clean config, and testing the tip of master (f99b78c). I was unable to reproduce the disk overflow behaviour. So I rolled back to 06ee5c9 ... and was _still_ unable to reproduce it.

I compared with my previous config and noticed I had set up the S3 backend, which I realise now I had forgotten to mention - sorry.

So now, the results:

* f99b78c = no problem
* f99b78c + S3 = no problem
* 06ee5c9 = no problem
* 06ee5c9 + S3 = problem

So it looks like whatever this bug was got fixed between 06ee5c9 and f99b78c. Given that 06ee5c9 is now in the past and was never pushed to the Hub, I'm not sure it's worth looking further, but here are the results anyway:

```json
{
 "CurrSize": 1033901900,
 "MaxSize": 1073741824,
 "NumFiles": 2967,
 "ServerTime": 1580724720,
 "GitCommit": "06ee5c920d92a33ea16011ede16f186f37f1ccf8"
}
```

```
# du -s .
3034552	.
# find -type f | wc -l
2967
```

So there's agreement on the file count, but the size is way out - 3GB vs a limit of 1.

Simply restarting the container causes a prune during the initial load of cache entries, so the behaviour does _kind of_ work - it's not totally unable to delete files:

```json
{
 "CurrSize": 879013197,
 "MaxSize": 1073741824,
 "NumFiles": 1345,
 "ServerTime": 1580724938,
 "GitCommit": "06ee5c920d92a33ea16011ede16f186f37f1ccf8"
}
```

```
# du -s .
863264	.
# find -type f | wc -l
1345
```

Given this change on master, I'm second guessing whether my disk issue is related to the memory problem originally reported. I think I'll just update our CI env to f99b78c and see what our monitoring graphs show over the next few days. If I see any more weird memory usage as time goes on, I'll dig into it again.

**Comment by mostynb** [comment]
I strongly suspect that these are two separate issues, and that the memory issue is an incorrect monitoring method rather than a memory leak in bazel-remote.

There are no functional changes between `06ee5c9` and `f99b78c` as far as I can tell, so the disk usage accounting issue is probably a race condition that doesn't occur every testrun. I will take a closer look at the cache size counting code.

**Comment by Zetten** [comment]
Yeah, looking at the diff there's no clear reason for the  success I'm seeing now. But it and the error case are pretty consistent over the last week or so of testing, and they're reproducible across two totally different kubernetes clusters with different S3 backend impls and disk storage backends. Still, I've had weirder issues with race conditions so I wouldn't rule it out!

**Comment by mostynb** [comment]
@Zetten: here's a test branch based on `f99b78c` with a /debug URL that loops over the LRU, checks the cache size is the sum of all the items in the LRU index, and prints the names of items that have a different size on disk compared to the index:
https://github.com/mostynb/bazel-remote/commit/0034fbb93d5d54f915647861e6929297dcf43695

If you could run this when the cache gets into a bad state, and while it's completely idle (no clients and no ongoing proxy traffic), this might help us to understand what's going on.

Since the index appears to have to correct number of items when it's in the bad state, it must either be that some of the items in the index have the wrong size, or if all the individual sizes are correct then the running currentSize value must be wrong.

**Comment by Zetten** [comment]
Yep, the issue arose again. Notably (but perhaps coincidentally) once the cache was under a slightly heavier load with multiple builds.

After everything settled down, here's the status page:
```
{
 "CurrSize": 3689911663,
 "MaxSize": 4294967296,
 "NumFiles": 12447,
 "ServerTime": 1580829695,
 "GitCommit": "4a12aeba52473fcc22b15976628e5af4d985cf52"
}
```

The debug page:
```
expected CurrentSize: 3689911663
expected NumItems: 12447
Actual CurrentSize: 5133656857 Expected: 3689911663
No bad items found.
```

And the real disk stats:
```
# find . -type f | wc -l
12926
# du -s .
5058204	.
```

(Interesting that the file count on disk is different this time...)

**Comment by mostynb** [comment]
@Zetten: thanks- I have located a couple of issues and managed to reproduce them in a stress test. I will hopefully have a fix for you to try tomorrow.

**Comment by mostynb** [comment]
@Zetten: I think #176 might be the cause of the disk over-usage you're seeing. Possible fix in #177 (and another slightly related fix in #178).

**Comment by Zetten** [comment]
@mostynb Thanks, let's move discussion to #176.

@mehmetg Sorry for derailing this issue!

**Comment by mehmetg** [comment]
No worries! I have been preoccupied for work related emergencies... I'll try tp collect some data and share here. We have increased load on our instance quite a bit and are seeing some performance degradation as well.

**Comment by mostynb** [comment]
@mehmetg: I'm not sure if you tried `GODEBUG=madvdontneed=1`, but if you try a new build from the master branch we now use go 1.16 which no longer needs this variable. From the release notes:

> On Linux, the runtime now defaults to releasing memory to the operating system promptly (using MADV_DONTNEED), rather than lazily when the operating system is under memory pressure (using MADV_FREE). This means process-level memory statistics like RSS will more accurately reflect the amount of physical memory being used by Go processes. Systems that are currently using GODEBUG=madvdontneed=1 to improve memory monitoring behavior no longer need to set this environment variable.

https://golang.org/doc/go1.16#runtime

**Comment by mehmetg** [comment]
This issue seems to have been resolved in the latest release. Thank you for the pointers and fixing it.
