### ISSUE TITLE
Can we have disable_ac_validation for gRPC?

### ISSUE THREAD

**Issue by brentleyjones** [buchgr/bazel-remote#231]
I love that we have `--disable_http_ac_validation`. Can we have a command that applies to both, or a new one that also applies to gRPC? I'm using bazel-remote as a backend for BuildBarn. Each cache instance is one of many and BuildBarn does the AC validation. Without this setting I can only use the HTTP mode of `bazel-remote`.

**Comment by mostynb** [comment]
I wasn't aware of that usecase- Interesting. I don't see why not, we just need to find a suitable name.

The reason I added the `--disable_http_ac_validation` flag was to support using bazel-remote as a network-accessible LRU cache for generic file blobs (unrelated to REAPI), so it does not check that the blobs are valid `ActionResult` protos, and as a result does not do any dependency checking.

For gRPC I think we can assume that all the blobs are valid `ActionResult` protos since that is handled by the gRPC framework- but you would like to simply skip checking for all the dependent blobs in the CAS if this new flag is specified? I'm torn between `--disable_grpc_ac_validation` (consistent with the other flag, but slightly inaccurate) and something like `--disable_grpc_ac_dependency_check` (a bit of a mouthful).

**Comment by brentleyjones** [comment]
I would vote for checking that it’s valid, just not the dependency checking. As for naming, I’ll leave that for you. Maybe we make it apply to both gRPC and HTTP since in both cases we would want the AC to be valid but maybe not check the dependencies?

**Comment by mostynb** [comment]
Here's a quick hack for you to test:
https://github.com/mostynb/bazel-remote/tree/disable_grpc_ac_deps

If this works, and if it's somehow better than using HTTP, then I can clean it up before landing. But I suspect it might not be much different to just using HTTP. Please let me know how it goes.

(The original purpose of `--disable_grpc_ac_validation` was to allow arbitrary data, so the behaviour needs to differ for gRPC.)

**Comment by brentleyjones** [comment]
Thanks @mostynb. I’ll check it out Monday.

**Comment by brentleyjones** [comment]
That is better, but something is still slightly off. When running in HTTP mode with validation disabled I can get 100% cache hits with two instances split. With this I still don't get all cache hits.

**Comment by mostynb** [comment]
Do you have a small-enough testcase that you could capture the access logs for, starting with two empty bazel-remote instances?

**Comment by brentleyjones** [comment]
I'll look into that, yes.

**Comment by brentleyjones** [comment]
For proper tracking, https://github.com/buchgr/bazel-remote/pull/234#issuecomment-602703339 (which I should have posted here).

**Comment by brentleyjones** [comment]
My testing must have been wrong. I forced the `!s.depsCheck` code path and it worked. I'll try again without the force to verify if it was the check or me not compiling things correctly the first time.

**Comment by brentleyjones** [comment]
Yep, so it's something with the plumbing of the `disable_grpc_ac_deps` flag. The code path worked when I changed `!s.depsCheck` to `true`, but doesn't otherwise.

**Comment by mostynb** [comment]
Thanks. I'll fix the plumbing and clean this up tomorrow.

**Comment by brentleyjones** [comment]
Resolved by #235.
