### ISSUE TITLE
Bazel-remote doesn't support Security Token Service (STS) authentication for S3

### ISSUE THREAD

**Issue by JSGette** [buchgr/bazel-remote#490]
So I created an S3 bucket in AWS and all required policies. Bazel-remote is working when used within EC2 Instance with attached policy. But if I am trying to run bazel-remote locally with credentials configured in ~/.aws/credentials I am getting 408 Request Timeout even if I use `aws sts --profile PROFILE_NAME get-caller-identity`. I also tried to set a profile via environment variable (export AWS_PROFILE=PROFILE_NAME), it didn't have any effect.

**Comment by mostynb** [comment]
Hi, bazel-remote doesn't use ~/.aws/ configuration - you would need to create a bazel remote config file and specify the account details there. There's a commented example in the readme file.

**Comment by mambon2** [comment]
@justfalter @mostynb I was reading this quote from aws aws/aws-cli#4982 (comment)
In it they state the following:

As of now, all AWS SDKs except C++ support the credentials from SSO login.

Is this true for this goapp? If so, which authentication method should we use to leverage sso login (instead of credentials file)

**Comment by mostynb** [comment]
I think there are details on how to do this over here: https://github.com/buchgr/bazel-remote/pull/493#issuecomment-984803190
