### ISSUE TITLE
use the remote asset api as a yarn or npm cache

### ISSUE THREAD

**Issue by err0r500** [buchgr/bazel-remote#500]
Hello,
I try to use the remote asset api in order to cache the node dependencies of a test project (in replacement of restoring the yarn cache another way) and I can't get it working.

Am I missing the purpose of this flag ? Do I have to use a specific strategy in order to achieve that ?

Best,
Matthieu

**Comment by mostynb** [comment]
Hi, I'm not familiar with nodejs.

Are you using bazel to build your app? If so, you can add `--experimental_remote_asset_api` to your bazel-remote flags, and `--experimental_remote_downloader=grpc://your.bazel.remote.host:port` and `--remote_cache=grpc://your.bazel.remote.host:port` to your bazel flags, and bazel will try to fetch archives from your WORKSPACE file from bazel-remote instead of the (slow?) internet.

**Comment by err0r500** [comment]
Thanks a lot @mostynb 
Actually, that's already what I do but I wouldn't be surprised it's a node-specific behavior.

I'll investigate the nodejs_rules part of the problem. If I find something, I'll update this issue for newcomers like me.

Thanks again, for this great project!

**Comment by mostynb** [comment]
I would have guessed this was core bazel behaviour, but I don't know bazel internals particularly well. Can you point me to a small node project that uses bazel to try building?

> Thanks again, for this great project!

I'm glad you find it useful :)

**Comment by mostynb** [comment]
Closing this for now due to lack of details, please reopen if this is still a problem.
