### ISSUE TITLE
Is it safe to run multiple instances of bazel-remote pointing at the same NFS directory?

### ISSUE THREAD

**Issue by hq6** [buchgr/bazel-remote#508]
I am attempting to use bazel-remote to perform Bazel Remote Caching on a set of CI servers that share an NFS server. I cannot use a disk cache because the project I am building is built in Docker.

My current approach is to dynamically start instances of bazel-remote when CI runs, and serve the NFS path. That means if multiple builds run concurrently, multiple instances of bazel-remote will be running (on different machines and ports), while serving the same directory.

Is it safe to run multiple instances of bazel-remote pointing at the same NFS directory?
Relatedly, will I lose many of the benefits of the cache even if it is safe?

**Comment by mostynb** [comment]
I would expect to see cache size limit issues with a setup like that- one bazel-remote instance won't know about uploads received by other bazel-remote instances that are currently running. I think it would work much better (and simpler) if you had a single permanently running instance of bazel-remote and point the clients at it.

**Comment by hq6** [comment]
**Is failing to respect the cache size limit temporarily the only problem I'd expect to see with this setup?** 

I ask because each of my bazel-remote instances would only live as long as necessary, so if I go over briefly and it's corrected when the next instance loads, I'm not particularly concerned.

While I agree that in the common case, it's simpler to have a single permanently running instance, in my particular case, starting instances on-demand is actually easier. This is because I have no control over the networking outside of the single CI machine my job is scheduled on and getting security approvals to host a permanent server available to my CI environment is nontrivial.

**Comment by mostynb** [comment]
It's untested, but I think bazel-remote shouldn't crash or return bad results when run in this way. It could return some false cache misses, and startup might become slow, but maybe that's acceptable for you.

**Comment by hq6** [comment]
Thanks! I've been thinking about this some more and I think my biggest
concern is cache corruption.

Just to double check, does Bazel remote take any kind of file lock before
reading or writing a file? Equivalently, are file writes always atomic?

The race I worry about is if two instances both query and then both try to
write the same data to the same file, and somehow we get half a file
written.

**Comment by mostynb** [comment]
Bazel-remote attempts to have atomic cache writes, each upload is written to a filename with a random string (so different uploads are written to different files), and only once a file is successfully written to disk and synced is it added to the in-memory index. We attempt to protect against cache corruption in case bazel-remote exits while writing files by creating them with the setgid bit set, and unsetting the setgid bit once the file is written, synced and closed. Bazel-remote won't import cache files with setgid bit set, and it will remove incomplete/broken files in the cache dir (to avoid leaking disk space).

One case I would worry about is if a bazel-remote instance (A) starts and is scanning the filesystem for cache files while another bazel-remote instance (B) is running and writing a large file to disk- what happens if instance A removes the incomplete file that B is writing to? I suspect that the file will be removed, instance B will finish writing, sync and close the file, which succeeds but is now deleted, and the deleted filename is added into B's cache index. If instance B later has a read request for that blob, it will at best successfully return a cache miss.

**Comment by hq6** [comment]
Thanks for the clarifications into how `bazel-remote` handles consistency semantics!
