### ISSUE TITLE
end-to-end test is stuck on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [buchgr/bazel-remote#519]
https://buildkite.com/bazel/bazel-remote-cache/builds/2225#19fbe5d6-5efd-4c2c-998a-9f3d33343da2

This job timed out after stucking for 8 hours.

There is no CI infra change or any commit to bazel-remote in the meantime. Please check if the tools downloaded in https://github.com/buchgr/bazel-remote/blob/master/.bazelci/system-test.sh contain any update that caused this.

**Comment by mostynb** [comment]
I think the minio tools downloaded in system-test.sh might have changed. Investigating...

**Comment by mostynb** [comment]
Disabled this test on the master branch to avoid wasting resources in nightly builds, while I try to figure out what's going on (these tests seem to work locally).

**Comment by mostynb** [comment]
This started working again without any changes from me. I think the problem was a bug in mc or minio, but I couldn't find versioned binaries to download, only the most recent release.

So I added 30 minute timeouts to the slower tests in case it happens again: https://github.com/buchgr/bazel-remote/pull/520/files (I wonder if this is possible to do in yaml instead?)

**Comment by meteorcloudy** [comment]
Thanks! 
> I wonder if this is possible to do in yaml instead?

Nope, it's currently not possible.
