### ISSUE TITLE
Race condition during concurrent bazel-remote cache deployment

### ISSUE THREAD

**Issue by jgao54** [buchgr/bazel-remote#573]
Context: we are getting started with bazel-remote and have a non-sharded singleton cache.  During blue/green deployment, our strategy is spinning up the new cache server, mounting it to the same disk storage as the old cache server, flip 100% of traffic from old to new server at once, and finally tear down the old server.

Problem: we encountered the following error today:
> Loading of existing cache entries failed due to error: lstat /data/ac.v2/<SOME_ENTRY>: no such file or directory
> Error while walking directory: lstat /data/cas.v2/<SOME_ENTRY>: no such file or directory

This looks like a race condition that can happen, with existing server evicting an entry in the disk cache, while a new server is loading the disk cache and trying to read it via [filepath.Walk](https://github.com/buchgr/bazel-remote/blob/897df094a365d280b6fe9374da0748d4ea9a39fd/cache/disk/disk.go#L515-L533), triggering the above error.

Would it make sense to make this a non-fatal error if file is not found? Or does this potentially affect the integrity of the cache?

Separately, I believe this deployment approach means it's possible the initialization misses some cache entries due to race condition (which potentially affects the eviction policy for those entries), but not sure if there are other source of inconsistencies this could introduce.

Thanks!

**Comment by mostynb** [comment]
Bazel-remote maintains a running count of the disk usage from all the cache entries it knows about, because querying disk usage in a directory can be very slow. If there are two concurrent bazel-remote instances using the same cache dir, the disk usage can be undercounted (maybe not a huge problem), and some client configurations like bazel's "build-without-the-bytes" setup can break (a larger problem).

I suppose you could change this error into a warning if you're OK with these potential issues in a local bazel-remote fork, but this feels too confusing/risky to enable by default for all bazel-remote users.

Maybe it would be better to make your clients continue without using the cache server if it becomes unreachable, so a little downtime while restarting bazel-remote isn't a problem? It should be possible to run bazel-remote for months at a time.

**Comment by jgao54** [comment]
Thanks for the context :) We can definitely adjust our deployment strategy accordingly to tolerate a bit of downtime.  Just wanted to sanity-check this error guardrail is intended here.

Re: build-without-the-bytes, given that it currently does not support eviction; it makes using disk cache without eviction a pretty expensive strategy (relative to s3/gcs). However i imagine later on eviction could be supported by build-without-the-bytes.

**Comment by mostynb** [comment]
> Just wanted to sanity-check this error guardrail is intended here.

Yes, though the guardrail could be nicer. I'm considering ways to add a cache directory lock file, which would be safer, and give a better error message earlier.

I'll close this issue for now, since this error is intentional.
