### ISSUE TITLE
Latest bazel-remote (2.4.1) fails to run on Ubuntu 18 due to GLIBC error

### ISSUE THREAD

**Issue by ericrafalovsky** [buchgr/bazel-remote#651]
# Summary
Running `bazel-remote` version 2.4.1 on Ubuntu 18 fails with the following error message:

`/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found`

Notably, bazel-remote version 2.4.0 works fine, so reporting this issue as perhaps there were some inadvertent changes in how this point release was packaged.

### Details 
bazel-remote version: 2.4.1
Ubuntu version: 18.04.5

**Comment by mostynb** [comment]
Github workflows stopped supporting ubuntu 18.04 recently, because it is EOL next month (according to https://wiki.ubuntu.com/Releases), so I had to upgrade the release builder to 20.04 (with the newer glibc). However If you make a local build of the 2.4.1 release on ubuntu 18.04, it should work OK.

I recommend that you upgrade to 20.04 or 22.04 soon though.

**Comment by mostynb** [comment]
I rebuilt the bazel-remote-2.4.1-linux-x86_64 binary on ubuntu 20.04 (instead of 22.04), and it seems to run OK on ubuntu 18.04 too. So I updated the binary in the bazel-remote 2.4.1 github release.
