### ISSUE TITLE
Please provide binary releases

### ISSUE THREAD

**Issue by ob** [buchgr/bazel-remote#77]
In the same way that Bazel provides binaries, `bazel-remote` should also provide binary releases.

**Comment by zoidbergwill** [comment]
We could use this GitHub action [here](https://github.com/ngs/go-release.action)

I tested it out on my fork below. The only strange/unnecessary thing is that it's creating `.tar.gz`'s of the binaries, instead of the pure binary. The action's repo has an issue open to address that [here](https://github.com/ngs/go-release.action/issues/2), but the repo seems a bit dead.

GitHub workflow file: https://github.com/zoidbergwill/bazel-remote/blob/master/.github/main.workflow
GitHub Actions logs: https://github.com/zoidbergwill/bazel-remote/runs/155254550
Release I created with generated binaries: https://github.com/zoidbergwill/bazel-remote/releases

**Comment by mostynb** [comment]
@buchgr: if we start doing this now, I guess we need to decide what to call the current version. How about either 0.5.0 pr 1.0.0?

**Comment by buchgr** [comment]
I agree that we should be doing releases. Thanks for pushing this forward. I would be fine with 1.0.0 as it signals stability. Would you then want to follow semantic versioning?

**Comment by mostynb** [comment]
I think semantic versioning would make sense. It would be good to synchronise this with dockerhub updates if possible.

**Comment by buchgr** [comment]
I agree. I am not an expert on docker versioning. I believe how this is typically handled is that one tag's releases and have a latest tag pointing to the latest release or master.

**Comment by mostynb** [comment]
@zoidbergwill: I would prefer not to use binaries built with "go build" as in that github action, because the results will be different to bazel-remote's "standard" build using bazel (and also different to those built with the linux-build.sh script). It would be better to use binaries built from bazelci/buildkite if possible.

@buchgr: I think we should call https://github.com/buchgr/bazel-remote/commit/a32c60af2b8fd0219d35301dbaacec5abcbf5c9d v1.0.0 - the last commit before I refactored the cache interface. If this is OK with you, I'll do that and then manually attach binaries to the release.

**Comment by mostynb** [comment]
Tagged v1.0.0, and manually uploaded mac + linux binaries using a similar naming scheme to bazel's releases:
https://github.com/buchgr/bazel-remote/releases

**Comment by buchgr** [comment]
I believe this can be closed. Thanks @mostynb !
