### ISSUE TITLE
Proposal: manage cache in deffrent namespace

### ISSUE THREAD

**Issue by hyphennn** [buchgr/bazel-remote#793]
Hi, there. I wonder is it possible to support seperate caches into deffrent namespace?

# Background
## Why need namespace
Here is background: my company is novice to use bazel. So I met some problems when using bazel-remote: some users are always worried about the hermeticity. Some of their rules are self-made, and it's hard to always keep hermeticity. So they want to manage their caches seperately.

## Why not use instance
I know there is instance for this. But instance still has at least problems below: 
- it is almost impossible to manage caches. Once any user wanna clear their caches, you should clear all instances. 
- Some users are still worried about collision, because the function to calculate instances may be in-hermeticity.
- Now, our solution is offer diffrent cluster to diffrent user. But, it really cause waste of machine. 

And I know it's almost impossible to collide, but you know, it's hard to ask anybody to take the risk.

# Proposal
I think it will be useful to provide a 'namespace', which may looks like:
```
bazel build xxx --remote-cache=http://domain.com/namespace/instance
```
The storage will be like:
```
--cache-dir
   -- ac.v2
   -- cas.v2
   -- raw.v2
   --namespace1
      -- ac.v2
      -- cas.v2
      -- raw.v2
   --namespace2
      -- ac.v2
      -- cas.v2
      -- raw.v2
```
The origin storage will still work as 'default namespace'.

I'm not sure if this is a reasonable propalsal for a project linked to bazel remote-cache protocal. If it is basically ok, I'm happy to work on it.

**Comment by mostynb** [comment]
Hi, if you want completely separate caches, then I think the simplest thing to do is run multiple instances of bazel-remote using separate cache directories. They could be listening on different addresses on the same machine (eg using different ports). This will also prevent cache entries from one instance being evicted by cache uploads to another instance.

Also note that if you want to remove cache entries from bazel-remote's storage directory, then you will need to restart bazel-remote, or it will give incorrect responses to certain client requests (since the in-memory index will be out of sync with the state on disk). So using multiple bazel-remote instances would also help minimise downtime (other instances would be unaffected during cleanup).

**Comment by hyphennn** [comment]
Ok，that's really a helpful solutions, thanks a lot. I'll have a try.
